kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spotinst-api-access
  namespace: tectonic-system
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["nodes", "pods", "replicationcontrollers", "services", "limitranges"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
