kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spotinst-api-access
subjects:
- kind: ServiceAccount
  name: spotinst-api-access
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: spotinst-api-access
  apiGroup: rbac.authorization.k8s.io
