kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: spotinst-api-access
  namespace: default
subjects:
- kind: ServiceAccount
  name: spotinst-api-access
  namespace: default
roleRef:
  kind: ClusterRole
  name: spotinst-api-access
  apiGroup: rbac.authorization.k8s.io
